-f option makes rm much easier :-)
MarcManiez/libft pull request #2
Opened 2016-09-19 12:02 UTC by EricManiez

2016-09-22 18:06 UTC, MarcManiez commented on makefile
> +	ranlib $(NAME)
Can you sell me on ranlib? What can I do with this that I couldn't before?

2016-09-22 18:07 UTC, MarcManiez commented on makefile
> +	rm -f $(filenameso)
What's the thinking behind writing this in multiple lines? #flyfucking

2016-09-22 18:09 UTC, MarcManiez commented on makefile
>  			ft_atoi.c \
Is placing this on multiple lines mostly an aesthetic choice? Either way I can dig it.

2016-09-22 18:10 UTC, MarcManiez commented on makefile
> +NAME = libft.a
I'm not sure I get the advantage of not hardcoding it, here. Doesn't adding a variable just make things harder for that poor little computer of ours?

2016-09-22 18:12 UTC, MarcManiez requested changes
J'ai enculé toutes les mouches. En environnement pro, je crois que j'aurai tout laissé passer sans questions histoire d'aller vite, mais vu que j'essaie d'apprendre un max, j'ai posé toutes mes questions.

2016-09-23 08:33 UTC, EricManiez commented on makefile
> +NAME = libft.a
It does, but it also makes it a lot easier for you to reuse your Makefile for something else afterwards.

2016-09-23 08:33 UTC, EricManiez commented on makefile
>  			ft_atoi.c \
Aesthetic, and useful if there's one or more files you don't want to compile for some reason.
Much easier to comment out.

2016-09-23 08:33 UTC, EricManiez commented on makefile
> +	rm -f $(filenameso)
Could do it in one line.
Or maybe you'll want to comment out only one of the instructions someday, and it'll be a lot faster to do so with 2 separate instructions !

2016-09-23 08:33 UTC, EricManiez commented on makefile
> +	ranlib $(NAME)
It's supposed to index your library to make it faster.
As you can see, I don't know too much about the subject.

2016-09-23 08:36 UTC, MarcManiez approved these changes
Let's do this.

2016-09-23 08:36 UTC, merged